spring:
  application:
    name: MovieApp

  datasource:
    url: jdbc:oracle:thin:@localhost:1522:xe
    username: movie_app
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver

omdb:
  api:
    url: https://www.omdbapi.com
    key: b0223e15

movie:
  jwt:
    secret: mySecretKey
    expirationMs: 86400000
